-- Burhan Books, 4 of 4: the book the shop starts with.
-- Generated by scripts/make-seed-sql.mjs from src/data/books.seed.json.
-- Taken word for word from the old site. Price and payment link are left
-- empty for the owner to add in the admin. Running this again never
-- overwrites a book that's already there.

insert into public.books (slug, title, author, contributors, description, price_pence, cover_url, cover_small_url, cover_width, cover_height, is_published, sort_order, updated_at)
values
  ($seed$shii-theology-a-translation-of-kashf-al-murad$seed$,
   $seed$Shi’i Theology: A translation of Kashf al-Murad$seed$,
   $seed$‘Allamah al-Hilli$seed$,
   $seed$Translated, introduced, and annotated by Fadil Asadi Amjad and Mahdi Dasht Bozorgi$seed$,
   $seed$*Shi‘i Theology* is a translation of the seminal Arabic work ***Kashf al-Murad fi Sharh Tajrid al-I‘tiqad***, a cornerstone of Twelver Shi‘i theology that has long served as a foundational textbook in seminaries. It is the most distinguished commentary on *Tajrid al-I‘tiqad by *Nasir al-Din al-Tusi’s (d. 1274) whose life and contributions are detailed in the prefatory section.

The first part of the book examines the concept of Allah, presenting compelling arguments for His existence and the necessity of a Creator. This section delves into intricate discussions on divine essence, attributes, and actions, as well as philosophical matters such as existence and nonexistence, cause and effect, substances and accidents, the definition of good and evil, and the problem of theodicy.

The second part explores the divine-human relationship, starting with prophethood, the necessity of prophethood, infallibility, and the Prophet Muhammad. It then delves into imamate, discussing the necessity of imamate, the nature of the Imam, arguments supporting Imam ‘Ali’s succession to the Prophet, and a historical overview of events at the end of the Prophet’s life. The book concludes with sections on the afterlife – covering resurrection, intercession, repentance, and the topography of the Hereafter – alongside a section on the principles of enjoining good and forbidding evil.

This comprehensive examination of Shi‘i theology is a must-read for anyone seeking to understand the core beliefs and principles of Shi‘ism in depth.

**Hasan ibn Yusuf ibn Mutahhar al-Hilli** (1250–1325), widely renowned as **‘Allamah al-Hilli** (‘the sage of Hillah’), was a distinguished fourteenth-century Twelver Shi‘i jurist and theologian. Born in Hillah, Iraq, al-Hilli initially studied religious sciences under the tutelage of his father and uncle, later expanding his education to encompass philosophy, logic, and astronomy. By the age of 28, he had achieved the status of a *mujtahid*.

An incredibly prolific writer, al-Hilli authored over a hundred books on a diverse array of subjects, including jurisprudence, principles of jurisprudence, doctrine, and theology. Many of these works remain influential today. Owing to his immense knowledge, he became the first scholar to receive the prestigious title of “ayatollah.”

After relocating to Iran, al-Hilli debated scholars from the four Sunni schools of thought, ultimately emerging victorious. His triumph led Sultan Muhammad Khudabanda to embrace Shi‘ism, contributing to the spread of Shi‘ism throughout Iran. While al-Hilli was in Iran, he was said to have had a mobile school made of tents, so that he could continue teaching during his travels. He was laid to rest in the shrine of Imam ‘Ali in Najaf, Iraq.

**Nasir al-Din al-Tusi** (1201-1274) was a distinguished Shi‘i philosopher, scientist, and theologian, and a towering figure in the realm of Islamic thought. Having endured the turbulent period of the Mongol conquests, al-Tusi later ascended to prominence as an advisor to the Mongol rulers, inspiring several of them to embrace Islam.

As a polymath, al-Tusi made significant contributions to various fields, including mathematics, astronomy, and philosophy. He established the renowned Maragheh Observatory, which became a centre of scientific advancement during his time. An accomplished author, al-Tusi penned numerous books, further solidifying his reputation as one of the most influential thinkers in Islamic history.$seed$,
   null,
   $seed$/img/books/shii-theology-kashf-al-murad.jpg$seed$,
   $seed$/img/books/shii-theology-kashf-al-murad-300.jpg$seed$,
   468,
   746,
   true,
   0,
   $seed$2025-07-10T16:16:48+01:00$seed$)
on conflict (slug) do nothing;
